import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1785034449867 implements MigrationInterface {
    name = 'InitialSchema1785034449867'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_profiles" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "phone" character varying(20), "date_of_birth" date, "gender" character varying(30), "ci" character varying(20), "height_cm" numeric(5,2), "experience_level" character varying(50), "medical_conditions" text, "favorite_sports" jsonb, "avatar_url" character varying(500), "username" character varying(50), CONSTRAINT "UQ_6ca9503d77ae39b4b5a6cc3ba88" UNIQUE ("user_id"), CONSTRAINT "UQ_8d61760530794a59e5ac4b8a1ac" UNIQUE ("ci"), CONSTRAINT "UQ_7bdaa0714f4c1087a926a2d8369" UNIQUE ("username"), CONSTRAINT "REL_6ca9503d77ae39b4b5a6cc3ba8" UNIQUE ("user_id"), CONSTRAINT "PK_1ec6662219f4605723f1e41b6cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "code" character varying(100) NOT NULL, "name" character varying(100) NOT NULL, "description" text, "resource" character varying(50) NOT NULL, "action" character varying(20) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" SERIAL NOT NULL, "role_id" integer NOT NULL, "permission_id" integer NOT NULL, "granted_at" TIMESTAMP NOT NULL DEFAULT now(), "granted_by" integer, CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "permissions" jsonb, "hierarchy_level" integer, "is_system_role" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gym_locations" ("id" SERIAL NOT NULL, "gym_id" integer NOT NULL, "address" character varying(255) NOT NULL, "city" character varying(100) NOT NULL, "latitude" numeric(10,8) NOT NULL, "longitude" numeric(11,8) NOT NULL, CONSTRAINT "UQ_2de151344b26876022c2deff074" UNIQUE ("gym_id"), CONSTRAINT "UQ_1c079bf70afb67f160c071c57e5" UNIQUE ("latitude", "longitude"), CONSTRAINT "REL_2de151344b26876022c2deff07" UNIQUE ("gym_id"), CONSTRAINT "PK_95985bdf8c6a303a5b396b0c016" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gym_schedules" ("id" SERIAL NOT NULL, "gym_id" integer NOT NULL, "day_of_week" character varying(10) NOT NULL, "opens_at" TIME NOT NULL, "closes_at" TIME NOT NULL, "is_holiday" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_3f2592946b810b753db77726102" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gym_activity_attendance" ("id" SERIAL NOT NULL, "gym_activity_schedule_id" integer NOT NULL, "user_id" integer NOT NULL, "check_in_time" TIMESTAMP NOT NULL DEFAULT now(), "check_out_time" TIMESTAMP, "status" character varying(20) NOT NULL DEFAULT 'CONFIRMED', CONSTRAINT "PK_9b7827c8174f96823d231416ead" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gym_activity_schedules" ("id" SERIAL NOT NULL, "gym_activity_id" integer NOT NULL, "instructor_id" integer, "day_of_week" character varying(10) NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "max_attendees" integer NOT NULL, "is_recurring" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_434b87d35b2c0b40359111cc8d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_gym_activity_schedules_activity_id" ON "gym_activity_schedules" ("gym_activity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_gym_activity_schedules_instructor_id" ON "gym_activity_schedules" ("instructor_id") `);
        await queryRunner.query(`CREATE TABLE "gym_activities" ("id" SERIAL NOT NULL, "gym_id" integer NOT NULL, "name" character varying(100) NOT NULL, "description" text, "default_duration_min" integer, "is_active" boolean NOT NULL DEFAULT true, "is_free_access" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_80d9765e64b5d8647e90be56898" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."machine_inventory_status_enum" AS ENUM('AVAILABLE', 'MAINTENANCE')`);
        await queryRunner.query(`CREATE TYPE "public"."machine_inventory_category_enum" AS ENUM('CARDIO', 'TREN_SUPERIOR', 'TREN_INFERIOR', 'ESPALDA', 'MULTIESTACION')`);
        await queryRunner.query(`CREATE TABLE "machine_inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "gym_id" integer NOT NULL, "name" character varying(150) NOT NULL, "status" "public"."machine_inventory_status_enum" NOT NULL DEFAULT 'AVAILABLE', "category" "public"."machine_inventory_category_enum" NOT NULL DEFAULT 'MULTIESTACION', "image_url" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_028645dd62ab9e97731d7fb1483" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_machine_inventory_gym_id" ON "machine_inventory" ("gym_id") `);
        await queryRunner.query(`CREATE INDEX "idx_machine_inventory_status" ON "machine_inventory" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_machine_inventory_category" ON "machine_inventory" ("category") `);
        await queryRunner.query(`CREATE INDEX "idx_machine_inventory_gym_status" ON "machine_inventory" ("gym_id", "status") `);
        await queryRunner.query(`CREATE TABLE "gyms" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "description" text, "max_capacity" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_open" boolean NOT NULL DEFAULT true, "parent_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, CONSTRAINT "UQ_60ed09fdc87fa782b761e1ac199" UNIQUE ("name"), CONSTRAINT "PK_fe765086496cf3c8475652cddcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "role_id" integer NOT NULL, "gym_id" integer, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "assigned_by" integer, "expires_at" TIMESTAMP, CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_user_id" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_role_id" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_gym_id" ON "user_roles" ("gym_id") `);
        await queryRunner.query(`CREATE TABLE "emergency_contacts" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "full_name" character varying(150) NOT NULL, "phone" character varying(20) NOT NULL, "relation" character varying(50) NOT NULL, "is_primary" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_8be191845b6fca1c4e5ba5bd7d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, "push_token" character varying(500), "otp_code" character varying(6), "otp_expires_at" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_is_active" ON "users" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "reservations" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "gym_activity_schedule_id" integer, "gym_id" integer, "activity_id" integer, "reservation_date" date NOT NULL, "start_time" TIME, "end_time" TIME, "status" character varying(20) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "cancelled_at" TIMESTAMP, "reminder_sent" boolean NOT NULL DEFAULT false, "created_by" integer NOT NULL, "qr_token" character varying(36), CONSTRAINT "UQ_c8c2c50cb160f3bc6de0cb9f3c9" UNIQUE ("qr_token"), CONSTRAINT "PK_da95cef71b617ac35dc5bcda243" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_reservations_user_id" ON "reservations" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reservations_schedule_id" ON "reservations" ("gym_activity_schedule_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reservations_user_status" ON "reservations" ("user_id", "status") `);
        await queryRunner.query(`CREATE TABLE "waitlist_entries" ("id" SERIAL NOT NULL, "reservation_id" integer, "user_id" integer NOT NULL, "gym_activity_schedule_id" integer NOT NULL, "position_in_queue" integer NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'WAITING', "notified_at" TIMESTAMP, "assigned_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bd0ef66fff81d3be7b7a1568a4d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "visits" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "gym_id" integer NOT NULL, "entered_at" TIMESTAMP NOT NULL, "exited_at" TIMESTAMP, "duration_min" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0b0b322289a41015c6ea4e8bf30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_visits_user_id" ON "visits" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_gym_id" ON "visits" ("gym_id") `);
        await queryRunner.query(`CREATE TYPE "public"."exercises_log_type_enum" AS ENUM('WEIGHT_REPS', 'REPS_ONLY', 'TIME_DISTANCE', 'TIME_ONLY')`);
        await queryRunner.query(`CREATE TABLE "exercises" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "description" text, "muscle_group" character varying(50) NOT NULL, "category" character varying(50), "exercise_type" character varying(30), "secondary_muscle_groups" jsonb, "equipment_required" character varying(100), "difficulty_level" character varying(30) NOT NULL, "youtube_video_id" character varying(20), "image_url" character varying(500), "is_active" boolean NOT NULL DEFAULT true, "log_type" "public"."exercises_log_type_enum" NOT NULL DEFAULT 'WEIGHT_REPS', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, CONSTRAINT "UQ_a521b5cac5648eedc036e17d1bd" UNIQUE ("name"), CONSTRAINT "PK_c4c46f5fa89a58ba7c2d894e3c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_exercises_muscle_group" ON "exercises" ("muscle_group") `);
        await queryRunner.query(`CREATE INDEX "idx_exercises_difficulty_level" ON "exercises" ("difficulty_level") `);
        await queryRunner.query(`CREATE TABLE "routine_exercises" ("id" SERIAL NOT NULL, "routine_id" integer NOT NULL, "exercise_id" integer NOT NULL, "order_position" integer NOT NULL, "sets_recommended" integer, "reps_recommended" character varying(50), "weight_recommended_kg" numeric(5,2), "day_of_week" character varying(20), "rest_seconds_between_sets" integer, "notes" text, "params" jsonb, CONSTRAINT "PK_1e557a3e724e3497b89112bfd6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "routines" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "description" text, "trainer_id" integer NOT NULL, "assigned_user_id" integer, "gym_id" integer, "difficulty_level" character varying(30) NOT NULL, "duration_weeks" integer, "is_template" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, CONSTRAINT "PK_6847e8f0f74e65a6f10409dee9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workout_sessions" ("id" SERIAL NOT NULL, "routine_id" integer, "user_id" integer NOT NULL, "gym_id" integer, "sport_type" character varying(50), "started_at" TIMESTAMP NOT NULL DEFAULT now(), "finished_at" TIMESTAMP, "status" character varying(20) NOT NULL DEFAULT 'IN_PROGRESS', "duration_seconds" integer, "calories_burned" integer, "notes" text, CONSTRAINT "PK_eea00e05dc78d40b55a588c9f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_active_session_per_user_routine" ON "workout_sessions" ("user_id", "routine_id") WHERE "finished_at" IS NULL AND "routine_id" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "workout_sets" ("id" SERIAL NOT NULL, "session_id" integer NOT NULL, "routine_exercise_id" integer, "exercise_id" integer, "set_number" integer NOT NULL, "reps_completed" integer, "weight_used_kg" numeric(5,2), "duration_seconds" integer, "distance_meters" integer, "rest_taken_seconds" integer, "metadata" jsonb, "completed_at" TIMESTAMP NOT NULL DEFAULT now(), "rating_perceived_exertion" integer, CONSTRAINT "PK_5ad75c97e58e8c660a48926d438" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_training_restrictions" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "restriction_type" character varying(50) NOT NULL, "description" text, "affected_body_areas" jsonb, "movements_to_avoid" jsonb, "requires_trainer_approval" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, CONSTRAINT "UQ_bebc456deb5ea970f69e7d6bfbb" UNIQUE ("user_id"), CONSTRAINT "REL_bebc456deb5ea970f69e7d6bfb" UNIQUE ("user_id"), CONSTRAINT "PK_3cf1f2255a6bba192a03b7672fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_training_goals" ("id" SERIAL NOT NULL, "user_training_id" integer NOT NULL, "primary_goal" character varying(50) NOT NULL, "experience_level" character varying(30) NOT NULL, CONSTRAINT "UQ_f3437190ad9956455026ad93e43" UNIQUE ("user_training_id"), CONSTRAINT "REL_f3437190ad9956455026ad93e4" UNIQUE ("user_training_id"), CONSTRAINT "PK_850a13cba8692b38fdd68694482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_training_preferences" ("id" SERIAL NOT NULL, "user_training_id" integer NOT NULL, "preferred_training_types" jsonb, "priority_body_areas" jsonb, "available_days_per_week" integer, CONSTRAINT "UQ_8ffd02c62ecbd821db10ab00183" UNIQUE ("user_training_id"), CONSTRAINT "REL_8ffd02c62ecbd821db10ab0018" UNIQUE ("user_training_id"), CONSTRAINT "PK_c39a971387ba8097d0a5e7d8a97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_training" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1dcf26aa5b956e6bf411a93be54" UNIQUE ("user_id"), CONSTRAINT "REL_1dcf26aa5b956e6bf411a93be5" UNIQUE ("user_id"), CONSTRAINT "PK_d9e0183d7238191e94b862cf4d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "system_settings" ("id" SERIAL NOT NULL, "setting_key" character varying(100) NOT NULL, "setting_value" jsonb NOT NULL, "description" text, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" integer, CONSTRAINT "UQ_9037e7dec102dfdfb0c5343807f" UNIQUE ("setting_key"), CONSTRAINT "PK_82521f08790d248b2a80cc85d40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "gym_id" integer, "description" text, "price_monthly" numeric(10,2) NOT NULL, "duration_days" integer, "sessions_included" integer, "window_days" integer, "scope" character varying(20) NOT NULL DEFAULT 'SUCURSAL', "max_gyms_access" integer, "features" jsonb, CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_subscriptions" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "plan_id" integer NOT NULL, "home_gym_id" integer, "status" character varying(20) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "auto_renew" boolean NOT NULL DEFAULT false, "reminder_sent" boolean NOT NULL DEFAULT false, "frozen_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, CONSTRAINT "PK_9e928b0954e51705ab44988812c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_active_membership_per_user" ON "user_subscriptions" ("user_id") WHERE "status" IN ('ACTIVA', 'ACTIVO', 'CONGELADA')`);
        await queryRunner.query(`CREATE TABLE "subscription_payments" ("id" SERIAL NOT NULL, "subscription_id" integer NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(10), "payment_date" TIMESTAMP NOT NULL DEFAULT now(), "method" character varying(30), "transaction_reference" character varying(60), "status" character varying(20) NOT NULL DEFAULT 'PAGADO', CONSTRAINT "PK_1b7a76365fd477de59cba0ab957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "membership_freeze_logs" ("id" SERIAL NOT NULL, "subscription_id" integer, "user_id" integer NOT NULL, "home_gym_id" integer, "performed_by_user_id" integer, "action" character varying(12) NOT NULL, "occurred_at" TIMESTAMP NOT NULL DEFAULT now(), "days_frozen" integer, "previous_end_date" date, "new_end_date" date, CONSTRAINT "PK_058ac411f1ca5ee8b6fb3080d9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_membership_freeze_logs_user_id" ON "membership_freeze_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_membership_freeze_logs_gym_id" ON "membership_freeze_logs" ("home_gym_id") `);
        await queryRunner.query(`CREATE INDEX "idx_membership_freeze_logs_occurred_at" ON "membership_freeze_logs" ("occurred_at") `);
        await queryRunner.query(`CREATE TABLE "membership_checkins" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "subscription_id" integer, "gym_id" integer NOT NULL, "checked_in_at" TIMESTAMP NOT NULL DEFAULT now(), "method" character varying(20) NOT NULL DEFAULT 'FACIAL', CONSTRAINT "PK_4f53328fbe9352bff4938f04476" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_membership_checkins_user_id" ON "membership_checkins" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_membership_checkins_gym_id" ON "membership_checkins" ("gym_id") `);
        await queryRunner.query(`CREATE TABLE "trainer_plans" ("id" SERIAL NOT NULL, "trainer_id" integer NOT NULL, "client_id" integer NOT NULL, "daily_kcal" integer, "protein_g" numeric(6,1), "carbs_g" numeric(6,1), "fat_g" numeric(6,1), "plan_notes" text, "meal_plan" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_trainer_client_plan" UNIQUE ("trainer_id", "client_id"), CONSTRAINT "PK_e5afa822d7e96773b6a23ac680d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_schedules" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "gym_id" integer NOT NULL, "day_of_week" integer NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, CONSTRAINT "PK_6484157e0a3264994b8572183ef" PRIMARY KEY ("id")); COMMENT ON COLUMN "staff_schedules"."day_of_week" IS '0=Domingo, 6=Sábado'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_staff_schedule" ON "staff_schedules" ("user_id", "gym_id", "day_of_week") `);
        await queryRunner.query(`CREATE TABLE "nutritional_appointments" ("id" SERIAL NOT NULL, "nutritionist_id" integer NOT NULL, "patient_id" integer NOT NULL, "date" date NOT NULL, "start_time" TIME NOT NULL, "appointment_type" character varying(100) NOT NULL DEFAULT 'CONSULTA', "status" character varying(20) NOT NULL DEFAULT 'PENDIENTE', "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b7c1f0a5906a636da14a183b23e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_advisors" ("id" SERIAL NOT NULL, "client_id" integer NOT NULL, "advisor_id" integer NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "target_sessions_per_week" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_client_advisor" UNIQUE ("client_id", "advisor_id"), CONSTRAINT "PK_08fb41c3dcd8deb1f3d4ad11941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_notification_preferences" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "enable_push" boolean NOT NULL DEFAULT true, "reservation_confirmations" boolean NOT NULL DEFAULT true, "class_reminders" boolean NOT NULL DEFAULT true, "cancellations_alerts" boolean NOT NULL DEFAULT true, "promotional_content" boolean NOT NULL DEFAULT false, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_816517663cdb51e17cd20947556" UNIQUE ("user_id"), CONSTRAINT "REL_816517663cdb51e17cd2094755" UNIQUE ("user_id"), CONSTRAINT "PK_2b30dfc697b16f75a55be54d464" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" SERIAL NOT NULL, "type" character varying(50) NOT NULL, "title_template" character varying(255) NOT NULL, "body_template" text NOT NULL, CONSTRAINT "UQ_39862b1a722590857df5d1b2e3e" UNIQUE ("type"), CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "template_id" integer, "title" character varying(255) NOT NULL, "body" text NOT NULL, "sent_at" TIMESTAMP NOT NULL DEFAULT now(), "read_at" TIMESTAMP, "status" character varying(20) NOT NULL DEFAULT 'SENT', CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "physical_metrics_history" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "recorded_at" TIMESTAMP NOT NULL DEFAULT now(), "gym_id" integer, "weight_kg" numeric(5,2), "body_fat_percentage" numeric(4,2), "muscle_mass_kg" numeric(5,2), "waist_cm" numeric(4,2), "chest_cm" numeric(4,2), "hip_cm" numeric(4,2), "mid_arm_cm" numeric(4,2), "thigh_cm" numeric(4,2), "calf_cm" numeric(4,2), "notes" text, CONSTRAINT "PK_c53731c63d7ef27d0de754af9f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" SERIAL NOT NULL, "client_id" integer NOT NULL, "trainer_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3f0174b99f6c8a7a0f5e8e6239" ON "conversations" ("client_id", "trainer_id") `);
        await queryRunner.query(`CREATE TABLE "direct_messages" ("id" SERIAL NOT NULL, "conversation_id" integer NOT NULL, "sender_id" integer NOT NULL, "content" text NOT NULL, "deleted_for_sender" boolean NOT NULL DEFAULT false, "deleted_for_receiver" boolean NOT NULL DEFAULT false, "is_deleted_for_all" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8373c1bb93939978ef05ae650d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "check_ins" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "gym_id" integer NOT NULL, "check_in_time" TIMESTAMP NOT NULL DEFAULT now(), "check_out_time" TIMESTAMP, "method" character varying(20) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'COMPLETED', "action_type" character varying(10), CONSTRAINT "PK_fac7f27bc829a454ad477c13f62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_check_ins_user_id" ON "check_ins" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_check_ins_gym_id" ON "check_ins" ("gym_id") `);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_a5afd4e09e8fc0646edb1d79933" FOREIGN KEY ("granted_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym_locations" ADD CONSTRAINT "FK_2de151344b26876022c2deff074" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym_schedules" ADD CONSTRAINT "FK_eaf18baf60fdaad080b64a63b11" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym_activity_attendance" ADD CONSTRAINT "FK_e71b79f9616fb6b8ddca9c19ff0" FOREIGN KEY ("gym_activity_schedule_id") REFERENCES "gym_activity_schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym_activity_attendance" ADD CONSTRAINT "FK_7700bd5eacdd0e746732f862008" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym_activity_schedules" ADD CONSTRAINT "FK_0e24c87f8ca1d1d02d2f9869fc2" FOREIGN KEY ("gym_activity_id") REFERENCES "gym_activities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym_activity_schedules" ADD CONSTRAINT "FK_ffb3046909432c84da093b5c5a8" FOREIGN KEY ("instructor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym_activities" ADD CONSTRAINT "FK_48f57847ac2cb82f2e96505a6cb" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "machine_inventory" ADD CONSTRAINT "FK_2511f08f9360cde574e0c7c9e06" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gyms" ADD CONSTRAINT "FK_dc976b324f3f84b2a7b16797627" FOREIGN KEY ("parent_id") REFERENCES "gyms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_07c96fdab149838b5a97927709a" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_6de6fefffe4a6d17de747bf8b9d" FOREIGN KEY ("assigned_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emergency_contacts" ADD CONSTRAINT "FK_1cf39ea46db44d95b34d58d3605" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_4af5055a871c46d011345a255a6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_a2a342f48fc4ff82191b4cd55f8" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_60b90b155740978aed882d3c839" FOREIGN KEY ("gym_activity_schedule_id") REFERENCES "gym_activity_schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_3337d4c8a4948cbe6eaf4633fc2" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_939ec7e0b21ef3d206e35ad14d1" FOREIGN KEY ("activity_id") REFERENCES "gym_activities"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "FK_b1001ee39bd4574e5a0b31dda29" FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "FK_accc0d911773551b2eed1a2ed72" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" ADD CONSTRAINT "FK_62557e95384f18304b838d9d8c5" FOREIGN KEY ("gym_activity_schedule_id") REFERENCES "gym_activity_schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_194460786aece8cab095bec7a75" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_4676ead6cae4b4562f309c17cc1" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routine_exercises" ADD CONSTRAINT "FK_1e3257412b3f18b7db29584aaa6" FOREIGN KEY ("routine_id") REFERENCES "routines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routine_exercises" ADD CONSTRAINT "FK_a53b55c6c91fdff79bb92f6dbec" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routines" ADD CONSTRAINT "FK_227762e608f52d7f5cf860d4d04" FOREIGN KEY ("trainer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routines" ADD CONSTRAINT "FK_ea0d25295d6e97a7a267d856999" FOREIGN KEY ("assigned_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routines" ADD CONSTRAINT "FK_debe0c09b2b00d7432ee9c2a7af" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" ADD CONSTRAINT "FK_286ccdc9341557e387ad6abe78b" FOREIGN KEY ("routine_id") REFERENCES "routines"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" ADD CONSTRAINT "FK_3a1ec9260afc530837db15579a5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" ADD CONSTRAINT "FK_7045a0e0659d34923b0efe234fa" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sets" ADD CONSTRAINT "FK_686d93a2b213ca76f120a45a2e3" FOREIGN KEY ("session_id") REFERENCES "workout_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sets" ADD CONSTRAINT "FK_97facc8d3f63f8b3a31e5cdfbdf" FOREIGN KEY ("routine_exercise_id") REFERENCES "routine_exercises"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sets" ADD CONSTRAINT "FK_9a3b700413f3f5c26ee17daabd1" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_training_restrictions" ADD CONSTRAINT "FK_bebc456deb5ea970f69e7d6bfbb" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_training_goals" ADD CONSTRAINT "FK_f3437190ad9956455026ad93e43" FOREIGN KEY ("user_training_id") REFERENCES "user_training"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_training_preferences" ADD CONSTRAINT "FK_8ffd02c62ecbd821db10ab00183" FOREIGN KEY ("user_training_id") REFERENCES "user_training"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_training" ADD CONSTRAINT "FK_1dcf26aa5b956e6bf411a93be54" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_settings" ADD CONSTRAINT "FK_301c531938f84c39fa5019e7465" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ADD CONSTRAINT "FK_b63d7d263a4861de11e53d5e8c9" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "FK_0641da02314913e28f6131310eb" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "FK_fe0520c7b2c1c5792446086491f" FOREIGN KEY ("plan_id") REFERENCES "subscription_plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "FK_3a858762d9cdeed53fa7c7a65fb" FOREIGN KEY ("home_gym_id") REFERENCES "gyms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_payments" ADD CONSTRAINT "FK_3d76b7ca2d964925a54ad9fd516" FOREIGN KEY ("subscription_id") REFERENCES "user_subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_freeze_logs" ADD CONSTRAINT "FK_1bfbafcc1deef39845e89e1bec6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_freeze_logs" ADD CONSTRAINT "FK_a1c13c3693b33037e05460dd273" FOREIGN KEY ("performed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_freeze_logs" ADD CONSTRAINT "FK_967d206751b5578649b699c49c0" FOREIGN KEY ("home_gym_id") REFERENCES "gyms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_freeze_logs" ADD CONSTRAINT "FK_36cf8bcbd45107b37ab5bd8042c" FOREIGN KEY ("subscription_id") REFERENCES "user_subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_checkins" ADD CONSTRAINT "FK_c74dd570c72f469c0bad9fe182c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_checkins" ADD CONSTRAINT "FK_38b5a723ecd7ae28427dd7ea7b1" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_checkins" ADD CONSTRAINT "FK_be5cc51deaaff15127467473ed1" FOREIGN KEY ("subscription_id") REFERENCES "user_subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_d630209d33108b76c7266013f56" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_d87fbbed9ab1346d1ef20498aaa" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutritional_appointments" ADD CONSTRAINT "FK_2acff20af2d6057f67bc3b9873c" FOREIGN KEY ("nutritionist_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutritional_appointments" ADD CONSTRAINT "FK_c5f8686e385fe7e5acf09d64936" FOREIGN KEY ("patient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_advisors" ADD CONSTRAINT "FK_0ccdc575e48768e11f55c7ddf5f" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_advisors" ADD CONSTRAINT "FK_8f30f910b3bc050994fad59fcf9" FOREIGN KEY ("advisor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification_preferences" ADD CONSTRAINT "FK_816517663cdb51e17cd20947556" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_e37d0438b1fffd0f210df30b271" FOREIGN KEY ("template_id") REFERENCES "notification_templates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "physical_metrics_history" ADD CONSTRAINT "FK_e46520e8a40b150d8bf2cfa33cf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "physical_metrics_history" ADD CONSTRAINT "FK_59736d76c4230944bfff052a122" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_6c66034346a5934cdc0dcb4a962" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_16ee79eac375142d338e55a60b2" FOREIGN KEY ("trainer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "direct_messages" ADD CONSTRAINT "FK_23b6ec745858aed8de854af3410" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "direct_messages" ADD CONSTRAINT "FK_867d7903affb6b677ca85674050" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "check_ins" ADD CONSTRAINT "FK_7b8c2fc47cf37006c80fc5e80a9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "check_ins" ADD CONSTRAINT "FK_22855f002f6361b21a27b230730" FOREIGN KEY ("gym_id") REFERENCES "gyms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "check_ins" DROP CONSTRAINT "FK_22855f002f6361b21a27b230730"`);
        await queryRunner.query(`ALTER TABLE "check_ins" DROP CONSTRAINT "FK_7b8c2fc47cf37006c80fc5e80a9"`);
        await queryRunner.query(`ALTER TABLE "direct_messages" DROP CONSTRAINT "FK_867d7903affb6b677ca85674050"`);
        await queryRunner.query(`ALTER TABLE "direct_messages" DROP CONSTRAINT "FK_23b6ec745858aed8de854af3410"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_16ee79eac375142d338e55a60b2"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_6c66034346a5934cdc0dcb4a962"`);
        await queryRunner.query(`ALTER TABLE "physical_metrics_history" DROP CONSTRAINT "FK_59736d76c4230944bfff052a122"`);
        await queryRunner.query(`ALTER TABLE "physical_metrics_history" DROP CONSTRAINT "FK_e46520e8a40b150d8bf2cfa33cf"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_e37d0438b1fffd0f210df30b271"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "user_notification_preferences" DROP CONSTRAINT "FK_816517663cdb51e17cd20947556"`);
        await queryRunner.query(`ALTER TABLE "client_advisors" DROP CONSTRAINT "FK_8f30f910b3bc050994fad59fcf9"`);
        await queryRunner.query(`ALTER TABLE "client_advisors" DROP CONSTRAINT "FK_0ccdc575e48768e11f55c7ddf5f"`);
        await queryRunner.query(`ALTER TABLE "nutritional_appointments" DROP CONSTRAINT "FK_c5f8686e385fe7e5acf09d64936"`);
        await queryRunner.query(`ALTER TABLE "nutritional_appointments" DROP CONSTRAINT "FK_2acff20af2d6057f67bc3b9873c"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_d87fbbed9ab1346d1ef20498aaa"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_d630209d33108b76c7266013f56"`);
        await queryRunner.query(`ALTER TABLE "membership_checkins" DROP CONSTRAINT "FK_be5cc51deaaff15127467473ed1"`);
        await queryRunner.query(`ALTER TABLE "membership_checkins" DROP CONSTRAINT "FK_38b5a723ecd7ae28427dd7ea7b1"`);
        await queryRunner.query(`ALTER TABLE "membership_checkins" DROP CONSTRAINT "FK_c74dd570c72f469c0bad9fe182c"`);
        await queryRunner.query(`ALTER TABLE "membership_freeze_logs" DROP CONSTRAINT "FK_36cf8bcbd45107b37ab5bd8042c"`);
        await queryRunner.query(`ALTER TABLE "membership_freeze_logs" DROP CONSTRAINT "FK_967d206751b5578649b699c49c0"`);
        await queryRunner.query(`ALTER TABLE "membership_freeze_logs" DROP CONSTRAINT "FK_a1c13c3693b33037e05460dd273"`);
        await queryRunner.query(`ALTER TABLE "membership_freeze_logs" DROP CONSTRAINT "FK_1bfbafcc1deef39845e89e1bec6"`);
        await queryRunner.query(`ALTER TABLE "subscription_payments" DROP CONSTRAINT "FK_3d76b7ca2d964925a54ad9fd516"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "FK_3a858762d9cdeed53fa7c7a65fb"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "FK_fe0520c7b2c1c5792446086491f"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "FK_0641da02314913e28f6131310eb"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" DROP CONSTRAINT "FK_b63d7d263a4861de11e53d5e8c9"`);
        await queryRunner.query(`ALTER TABLE "system_settings" DROP CONSTRAINT "FK_301c531938f84c39fa5019e7465"`);
        await queryRunner.query(`ALTER TABLE "user_training" DROP CONSTRAINT "FK_1dcf26aa5b956e6bf411a93be54"`);
        await queryRunner.query(`ALTER TABLE "user_training_preferences" DROP CONSTRAINT "FK_8ffd02c62ecbd821db10ab00183"`);
        await queryRunner.query(`ALTER TABLE "user_training_goals" DROP CONSTRAINT "FK_f3437190ad9956455026ad93e43"`);
        await queryRunner.query(`ALTER TABLE "user_training_restrictions" DROP CONSTRAINT "FK_bebc456deb5ea970f69e7d6bfbb"`);
        await queryRunner.query(`ALTER TABLE "workout_sets" DROP CONSTRAINT "FK_9a3b700413f3f5c26ee17daabd1"`);
        await queryRunner.query(`ALTER TABLE "workout_sets" DROP CONSTRAINT "FK_97facc8d3f63f8b3a31e5cdfbdf"`);
        await queryRunner.query(`ALTER TABLE "workout_sets" DROP CONSTRAINT "FK_686d93a2b213ca76f120a45a2e3"`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" DROP CONSTRAINT "FK_7045a0e0659d34923b0efe234fa"`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" DROP CONSTRAINT "FK_3a1ec9260afc530837db15579a5"`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" DROP CONSTRAINT "FK_286ccdc9341557e387ad6abe78b"`);
        await queryRunner.query(`ALTER TABLE "routines" DROP CONSTRAINT "FK_debe0c09b2b00d7432ee9c2a7af"`);
        await queryRunner.query(`ALTER TABLE "routines" DROP CONSTRAINT "FK_ea0d25295d6e97a7a267d856999"`);
        await queryRunner.query(`ALTER TABLE "routines" DROP CONSTRAINT "FK_227762e608f52d7f5cf860d4d04"`);
        await queryRunner.query(`ALTER TABLE "routine_exercises" DROP CONSTRAINT "FK_a53b55c6c91fdff79bb92f6dbec"`);
        await queryRunner.query(`ALTER TABLE "routine_exercises" DROP CONSTRAINT "FK_1e3257412b3f18b7db29584aaa6"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_4676ead6cae4b4562f309c17cc1"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_194460786aece8cab095bec7a75"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "FK_62557e95384f18304b838d9d8c5"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "FK_accc0d911773551b2eed1a2ed72"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entries" DROP CONSTRAINT "FK_b1001ee39bd4574e5a0b31dda29"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_939ec7e0b21ef3d206e35ad14d1"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_3337d4c8a4948cbe6eaf4633fc2"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_60b90b155740978aed882d3c839"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_a2a342f48fc4ff82191b4cd55f8"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_4af5055a871c46d011345a255a6"`);
        await queryRunner.query(`ALTER TABLE "emergency_contacts" DROP CONSTRAINT "FK_1cf39ea46db44d95b34d58d3605"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_6de6fefffe4a6d17de747bf8b9d"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_07c96fdab149838b5a97927709a"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "gyms" DROP CONSTRAINT "FK_dc976b324f3f84b2a7b16797627"`);
        await queryRunner.query(`ALTER TABLE "machine_inventory" DROP CONSTRAINT "FK_2511f08f9360cde574e0c7c9e06"`);
        await queryRunner.query(`ALTER TABLE "gym_activities" DROP CONSTRAINT "FK_48f57847ac2cb82f2e96505a6cb"`);
        await queryRunner.query(`ALTER TABLE "gym_activity_schedules" DROP CONSTRAINT "FK_ffb3046909432c84da093b5c5a8"`);
        await queryRunner.query(`ALTER TABLE "gym_activity_schedules" DROP CONSTRAINT "FK_0e24c87f8ca1d1d02d2f9869fc2"`);
        await queryRunner.query(`ALTER TABLE "gym_activity_attendance" DROP CONSTRAINT "FK_7700bd5eacdd0e746732f862008"`);
        await queryRunner.query(`ALTER TABLE "gym_activity_attendance" DROP CONSTRAINT "FK_e71b79f9616fb6b8ddca9c19ff0"`);
        await queryRunner.query(`ALTER TABLE "gym_schedules" DROP CONSTRAINT "FK_eaf18baf60fdaad080b64a63b11"`);
        await queryRunner.query(`ALTER TABLE "gym_locations" DROP CONSTRAINT "FK_2de151344b26876022c2deff074"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_a5afd4e09e8fc0646edb1d79933"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88"`);
        await queryRunner.query(`DROP INDEX "public"."idx_check_ins_gym_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_check_ins_user_id"`);
        await queryRunner.query(`DROP TABLE "check_ins"`);
        await queryRunner.query(`DROP TABLE "direct_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f0174b99f6c8a7a0f5e8e6239"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TABLE "physical_metrics_history"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP TABLE "user_notification_preferences"`);
        await queryRunner.query(`DROP TABLE "client_advisors"`);
        await queryRunner.query(`DROP TABLE "nutritional_appointments"`);
        await queryRunner.query(`DROP INDEX "public"."uq_staff_schedule"`);
        await queryRunner.query(`DROP TABLE "staff_schedules"`);
        await queryRunner.query(`DROP TABLE "trainer_plans"`);
        await queryRunner.query(`DROP INDEX "public"."idx_membership_checkins_gym_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_membership_checkins_user_id"`);
        await queryRunner.query(`DROP TABLE "membership_checkins"`);
        await queryRunner.query(`DROP INDEX "public"."idx_membership_freeze_logs_occurred_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_membership_freeze_logs_gym_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_membership_freeze_logs_user_id"`);
        await queryRunner.query(`DROP TABLE "membership_freeze_logs"`);
        await queryRunner.query(`DROP TABLE "subscription_payments"`);
        await queryRunner.query(`DROP INDEX "public"."uq_active_membership_per_user"`);
        await queryRunner.query(`DROP TABLE "user_subscriptions"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP TABLE "user_training"`);
        await queryRunner.query(`DROP TABLE "user_training_preferences"`);
        await queryRunner.query(`DROP TABLE "user_training_goals"`);
        await queryRunner.query(`DROP TABLE "user_training_restrictions"`);
        await queryRunner.query(`DROP TABLE "workout_sets"`);
        await queryRunner.query(`DROP INDEX "public"."uq_active_session_per_user_routine"`);
        await queryRunner.query(`DROP TABLE "workout_sessions"`);
        await queryRunner.query(`DROP TABLE "routines"`);
        await queryRunner.query(`DROP TABLE "routine_exercises"`);
        await queryRunner.query(`DROP INDEX "public"."idx_exercises_difficulty_level"`);
        await queryRunner.query(`DROP INDEX "public"."idx_exercises_muscle_group"`);
        await queryRunner.query(`DROP TABLE "exercises"`);
        await queryRunner.query(`DROP TYPE "public"."exercises_log_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_gym_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_user_id"`);
        await queryRunner.query(`DROP TABLE "visits"`);
        await queryRunner.query(`DROP TABLE "waitlist_entries"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reservations_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reservations_schedule_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reservations_user_id"`);
        await queryRunner.query(`DROP TABLE "reservations"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_is_active"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "emergency_contacts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_gym_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_user_id"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "gyms"`);
        await queryRunner.query(`DROP INDEX "public"."idx_machine_inventory_gym_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_machine_inventory_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_machine_inventory_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_machine_inventory_gym_id"`);
        await queryRunner.query(`DROP TABLE "machine_inventory"`);
        await queryRunner.query(`DROP TYPE "public"."machine_inventory_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."machine_inventory_status_enum"`);
        await queryRunner.query(`DROP TABLE "gym_activities"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gym_activity_schedules_instructor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gym_activity_schedules_activity_id"`);
        await queryRunner.query(`DROP TABLE "gym_activity_schedules"`);
        await queryRunner.query(`DROP TABLE "gym_activity_attendance"`);
        await queryRunner.query(`DROP TABLE "gym_schedules"`);
        await queryRunner.query(`DROP TABLE "gym_locations"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "user_profiles"`);
    }

}
